version: '2.1'

networks:
  monitor-net:
    driver: bridge
  ingress:
    external: true

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.13.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:v0.19.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net

  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:6.3.6
	restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=safePassword
      - GF_USERS_ALLOW_SIGN_UP=false
    expose:
      - 3000
    networks:
      - monitor-net
  pushgateway:
    image: prom/pushgateway:v1.0.0
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
  nginx:
    build: ./nginx
    volumes:
	  - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
	  - ingress
	  - monitor-net
    labels:
	  - traefik.enable=true
	  - traefik.network=ingress
	  - traefik.port=80
	  - traefik.backend=monitor
	  - "traefik.frontend.rule=Host:prometheus.kaii.com,grafana.kaii.com,alert.kaii.com,pihole.kaii.com"